### PR TITLE
Fix epsilon and varepsilon mixup

### LINKED ISSUE #9: epsilon and varepsilon appear to be backwards
This is what I get when I type these characters with 0.2.6

image

This is backwards from the definition of these characters in e.g. Python, [Latex](https://en.wikipedia.org/wiki/Epsilon#Unicode), and Julia, as well as the julia-vscode plugin and Atom's popular [latex-completions](https://atom.io/packages/latex-completions) plugin.  

Is that possbly motivation enough to swap them here too?

### PR DESCRIPTION
**Pull request by briochemc**
Fix #9

### CODE REVIEW

**Comment by briochemc** [comment]
Hi @gatapia,

Any chance you can take a look at this PR? I believe it fixes the mixup between epsilon and varepsilon throughout.

Cheers!

**Comment by gatapia** [comment]
I've merged but my marketplace access token no longer works.  I have
contact MS for assistance.  In the meantime you may need to build this
yourself.

**Comment by briochemc** [comment]
I think you might have to bump the version number too. Also, let me know if I can be of any help!

**Comment by gatapia** [comment]
Unofrtunately I can no longer deploy updates to the VS marketplace.  Their token system is broken and they have been no help.  Happy to add you to the project, perhaps you can get `vsce publish` to work.  Let me know if interested

**Comment by briochemc** [comment]
I have no idea how this all works so I'm not sure how I could help! (I thought maybe you knew but did not have the time and could give instructions and delegate)

**Pull request merged**
